public/bundle.css
public/bundle.js
views/mdc/assets/scss/components/list.scss
views/mdc/package-lock.json

Updated to latest MDC Added fix to unset 'content' style - this workaround fixes list secondary text having additional spacing. This may be able to be removed with future MDC updates.

Fixed bad styling in list line subtitle

---

lib/voom/presenters/web_client/app.rb

`WebClient::App` can't see `Errors::Unprocessable`, so
user/client app errors are being obscured by the Presenters
error:
'Unable to autoload constant Errors::Unprocessable, expected
/rx/presenters/lib/voom/presenters/errors/unprocessable.rb
to define it'
This precedes the custom error with the `Presenters` module
reference, so it may be found by `WebClient::App`.

Fix Unprocessable error type reference

---

views/mdc/components/buttons/button.erb
views/mdc/components/buttons/icon.erb
views/mdc/components/buttons/image.erb

Partially fixes #40:
* raised buttons are given `type="submit"`
* non-raised buttons are given `type="button"`

Decorate raised buttons with type="submit"

---

views/mdc/components/datetime.erb

Add conditional display of the datetime error/hint element,
as it's creating uneven vertical spacing with an empty
paragraph tag when no hint or error is present.

Fix vertical spacing for datetime component without message

---

public/bundle.css
views/mdc/assets/scss/components/rich-text-area.scss
views/mdc/components/rich_text_area.erb

The component wasn't spacing evenly in relation to other
elements. Remove the float from the label and let it
render in the normal flow, while giving it margin in
common with our other components.

Fix rich text area label positioning

---

lib/voom/presenters-engine.rb

Adding presenters to a new project initially generates
the error:
`undefined method 'require_dependency' for main:Object`
Scoping the method allows it to be found.

Fix `require_dependency` undefined error

---

lib/voom/presenters/dsl/components/google_map.rb
views/mdc/components/google_map.erb

These settings weren't working, updated to support map height
and width attributes.

Fix Google Map height/width attribute support

---

views/mdc/components/select.erb

Add missing local variable `comp` when rendering `components/event` from `components/select`

Add missing local when rendering components/event

---

views/mdc/components/text_area.erb

This fixes a bug which progressively pads text area values by one space character on each side when capturing and restoring a text area component's value.

Remove spaces around text area's value tag

---

lib/voom/railtie.rb

Currently, if you save a .pom with invalid Ruby in it, the
Thread that is watching this will die, and no poms will be
able to be rendered (the WebClient for presenters will just
quit). This change prevents the thread from dying, so you
can fix your .pom, and also prints a handy backtrace and message
so you can easily find your error.
This doesn't prevent the process from dying on first load if there is
invalid Ruby, but I think that's fine.

Prevent Filewatcher Thread from dying if it sees an invalid .pom

---

Gemfile.lock
app/demo/components/cards.pom
app/demo/plugins/image_crop.pom
lib/voom/presenters/dsl/components/button.rb
public/bundle.js
views/mdc/assets/js/components/base-component.js
views/mdc/assets/js/components/base-container.js
views/mdc/assets/js/components/dialogs.js
views/mdc/assets/js/components/events/toggle_visibility.js
views/mdc/assets/js/components/plugins.js
views/mdc/assets/js/components/text-fields.js
views/mdc/components/buttons/icon.erb

* Default behavior is no-op
* BaseContainer calls `reset()` on all its components
* Added `MDCDialog:opened` event listener to VDialog that calls `reset` on itself
The cropper plugin is using this functionality to rebuild itself when being shown on a dialog
MDC Components that may need to recalc their layout when going from a hidden to visible state
can use this method to do such (ie. `mdcComponent.layout()`)

* Added new `reset(){}` method to JS components

---

app/demo/components/dialogs.pom
views/mdc/components/dialog.erb

If you have both height and width, the style tag breaks because of no semicolon. I put in those and also defaulted the style to 'px' if an integer was input (previously you would have to put the unit into the pom)

Bugfix for dialog height/width, and documentation

---

views/mdc/assets/scss/components/fab.scss
views/mdc/components/button.erb

Allow FAB's position to be controlled via normal button `position` attribute values.
* Remove `position_classes` from button sub-components 
* Generate FAB-specific position classes and adjust base FAB styles
I've excluded regenerated bundle files from this PR as they'd likely generate a conflict with #114.

FAB position

---

lib/voom/presenters/dsl/user_interface.rb

initialize_plugins is only called when the UserInterface is
instantiated, at which point it has an empty array of plugins.
Afterwards they are collected, but not loaded. We need to load each
plugin as it is registered so its dsl is available.

Need to load plugins when they are registered

---

public/bundle.css
public/bundle.js
views/mdc/assets/js/components/base-toggle.js
views/mdc/assets/js/components/icon-toggles.js
views/mdc/assets/js/components/radios.js
views/mdc/assets/js/components/switches.js

This ensures checkboxes (which were missing the prepareSubmit method) submit a value in a manner consistent with other toggle components.

Move toggles' prepareSubmit method to VBaseToggle

---

app/demo/events/content_as_form.pom
public/bundle.js
public/wc.js
spec/integration/demo/00_index_spec.rb
spec/integration/demo/02_selectable_list_spec.rb
spec/integration/demo/03_content_as_form_spec.rb
spec/support/integration/host.rb
views/mdc/assets/js/components/base-component.js
views/mdc/assets/js/components/events/base.js
views/mdc/assets/js/components/events/posts.js
views/mdc/assets/js/components/events/prompt_if_dirty.js

Fix base Event and request FormData input collection logic.
* Ignore all falsey values for `input_tag`
* Previously, only `undefined` input_tag values were ignored, which allowed `null` input_tag values to be considered (although with no side effects).
* The `FormData` objects passed to `XMLHttpRequest` instances are now constructed manually rather than via passing an `HTMLFormElement` instance into the `FormData` constructor
* The native FormData constructor is problematic (for our use case) because it will ignore unchecked toggleable elements. This leads to different form data for `form` blocks vs. `content` blocks.
* The base event now gathers input values based on the following criteria:
1. If an `input_tag` is provided, all matching elements are included.
2. If the event's component …

Fix request params

---

public/bundle.js
public/style-bundle.js
public/wc.js
views/mdc/assets/js/components/base-container.js
views/mdc/assets/js/components/content.js
views/mdc/assets/js/components/events/base.js
views/mdc/assets/js/components/events/posts.js
views/mdc/components/card.erb
views/mdc/components/dialog.erb
views/mdc/components/form.erb

* Refactor base event input value collection
* Collected components are now more eagerly resolved to elements, and the resulting array of elements is deduplicated.
* Stop flagging grid and column as containers
* Flag cards and forms as containers
* Add missing `null` check for snackbar component usage
* Small dialog fixes
As of this PR, only the following components are considered containers:
* content
* form
* dialog
* card

Fix request params II

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/rich-text-area.js

Upon initialization, the value of the rich text area's `data-original-value` attribute will now be set to the component's value, which is the same value used for comparison by `VRichTextArea .isDirty()`.
This change should mitigate invisible HTML differences between the initial value and what the Quill editor renders into the component's DOM.

Fix dirty state of the rich text area component

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/base-container.js
views/mdc/assets/js/components/base-toggle.js
views/mdc/assets/js/components/datetime.js
views/mdc/assets/js/components/dialogs.js
views/mdc/assets/js/components/hidden-fields.js
views/mdc/assets/js/components/plugins.js
views/mdc/assets/js/components/rich-text-area.js
views/mdc/assets/js/components/selects.js
views/mdc/assets/js/components/sliders.js
views/mdc/assets/js/components/text-fields.js

* Allow input components to reset themselves
* Allow containers to reset their child input components
* Reset instead of clear dialog's input components when closing
* This fixes a bug which causes hidden fields to lose their value when a dialog is closed and later reopened.

Component reset

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/events/errors.js

Stop-gap fix for the nesting component of #131 without major refactoring.
* Handle nested error structures when normalizing response errors
* Only scroll errors `<div>` into view if it's off-screen
* Clean up

Display nested error structures

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/events/errors.js

Add handling for logical runtime errors like `"undefined method `map' for nil:NilClass"` (a plain string with no key).
Previously, `objectMap` would split the string into individual letters, resulting in an error message missing most of its letters split across multiple lines.

Handle logical runtime errors when displaying response errors

---

views/mdc/components/switch.erb

Clicking on the label of a disabled switch was toggling it because it
was only styled as disabled

Actually disable switches when set as such so they can't be toggled

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/base-component.js
views/mdc/assets/js/components/events/replaces.js

The removal of the <span> wrapper around a replaced element prevents the
hookupComponents logic from finding the element. If the provided root
matches the provided selector, include the root in the hookup logic.
This ensures the replaced element is properly initialized.

Conditionally include root when hooking up components

---

public/wc.js
views/mdc/assets/js/wc.js

`Document.prototype.registerElement` is not supported in non-Blink browsers.
This change replaces the call to `registerElement` with the preferred/supported `CustomElementRegistry.prototype.define` method.

Replace deprecated method for registering custom elements

---

public/bundle.css
views/mdc/assets/scss/components/header.scss
views/mdc/body/header.erb
views/mdc/layout.erb

This fixes and issue which incorrectly padded the top of the main content area in the absence of both a drawer and a header.

Use MDC class instead of sibling selector

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/base-container.js
views/mdc/assets/js/components/content.js
views/mdc/components/content.erb

This reverts the behavior of container classification to the state in f5d7c42.
At some point, the change in [f5d7c42](https://github.com/rx/presenters/commit/f5d7c429d787dfad110bfaf9903c0ab1fa7dddad#diff-18b58a6e1672a9752936c059ab3013c9L6) was reverted and the removed line was added back in, causing columns and grid to incorrectly be classified as containers for request payload collection purposes. This results in events which collect input values collecting far too many input values.

Revert container classification behavior

---

views/mdc/components/dialog.erb

There's a max-width property on mdc dialogs...let's remove that in the style tag if the user puts a width into their dialog.

Override max-width if width is set in dialog

---

lib/voom/presenters/demo/echo.rb
views/mdc/assets/js/components/text-fields.js

* Fix return value of `_echo_` endpoint in Demo
* Add dispatch of after_input event to text fields
* The text field will dispatch an `after_input` event once the user has stopped typing for 500 ms.

After input event

---

app/demo/styles.pom
lib/voom/presenters/dsl/components/link.rb
lib/voom/presenters/dsl/components/mixins/typography.rb
views/mdc/components/link.erb

The link component functions the same as a Markdown hyperlink and additionally allows a value for the `target` attribute to be specified.
Targets `blank` and `self` are supported, which expand to the equivalent HTML attribute value in the web client. The default target is `self`.

Add link component

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/button.js

Buttons will be unconditionally disabled when a `VPosts`-based request is issued and unconditionally enabled when the issued request has finished.

Toggle buttons for the duration of issued requests

---

lib/voom/presenters/dsl/components/text_field.rb
views/mdc/components/text_field.erb

* Allow `false`, `:disabled`, and `:off` to specify off
* Allow `true`, `:enabled`, and `:on` to specify on
* Pass through other values to the web client
* Map `auto_complete: :off` to `autocomplete="extra-off"` in the web client to make `:off` behave as expected

Change autocomplete to off by default

---

app/demo/components/icons.pom
lib/voom/presenters/web_client/app.rb
public/bundle.css
views/mdc/assets/scss/app.scss
views/mdc/assets/scss/palette.scss

add sample palette style sheet.
Allows use of `icon :thumbs-up color: [palette-color-name]` or `icon :thumbs-up color: [html-color-name]` and a palette color style will be applied if present.

Update color classes that are added on an icon based on `color` attribute,

---

lib/voom/presenters/dsl/components/input.rb
lib/voom/presenters/dsl/components/list.rb
lib/voom/presenters/dsl/components/lists/line.rb
public/bundle.js
public/wc.js
views/mdc/assets/js/components/checkboxes.js
views/mdc/components/checkbox.erb
views/mdc/components/datetime.erb
views/mdc/components/file_input.erb
views/mdc/components/hidden_field.erb
views/mdc/components/icon_toggle.erb
views/mdc/components/list/header.erb
views/mdc/components/radio_button.erb
views/mdc/components/rich_text_area.erb
views/mdc/components/select.erb
views/mdc/components/slider.erb
views/mdc/components/switch.erb
views/mdc/components/text_area.erb
views/mdc/components/text_field.erb

The list header checkbox is rendered as a standard checkbox component, but it should not be considered when checking for dirtied input elements.
Also make all input components optionally dirtyable.

Non-dirtyable list header checkbox

---

public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/button.js
views/mdc/assets/js/components/events.js
views/mdc/assets/scss/app.scss
views/mdc/assets/scss/components/button.scss
views/mdc/assets/scss/components/tooltip.scss
views/mdc/components/buttons/button.erb
views/mdc/components/buttons/fab.erb
views/mdc/components/buttons/icon.erb
views/mdc/components/buttons/image.erb
views/mdc/components/table/pagination.erb

* Implement `.v-button` CSS classes
* Ensure events are reinitialized correctly
* When replacing an element, the new root passed to component and event initialization is the replaced element itself (rather than the document or web component root).
* The component initializers were patched to include the replaced element if it matches the given selector, but this patch was not applied to the event initialization logic.
* This change remedies this, bringing event initialization up to par with component initialization.
* Bring icon button tooltip into its button element
* This fixes an issue which prevents tooltips from being properly reinitialized after a non-nested button is replaced.
* This is a stop-gap fix and does not work for other button types.

Fix icon buttons

---

public/bundle.js
public/wc.js
views/mdc/assets/js/components/events.js

An action from a plugin is resulting in an error that never gets
cleared.  Plugins only provide a function so don't have access to the
clearErrors() function and it makes sense to clear them when a new chain
begins as it will result in new errors or a clean run.

Clear errors before action chain

---

lib/voom/presenters/dsl/components/stepper.rb

When steppers were used and gave their buttons an event block to perform
actions such as post then we didn't have a promise chain that would
cancel, each event block was run.  This caused the stepper to move to
the next step when a post returned a 422.

Make stepper button events manual to avoid parallel actions

---

lib/voom/presenters/dsl/components/event_base.rb
lib/voom/presenters/dsl/components/header.rb
lib/voom/presenters/dsl/components/list.rb
lib/voom/presenters/dsl/components/lists/line.rb
lib/voom/presenters/dsl/components/typography.rb
lib/voom/presenters/web_client/app.rb
views/mdc/body/header.erb
views/mdc/components/list/line.erb
views/mdc/components/typography.erb

This provides a way to have raw text so user values can be straight
rendered and #foo won't result in a heading.  Any typography type can
take `markdown: false` to allow raw text.

Allow non markdown typography

---

lib/voom/presenters/api/app.rb
lib/voom/presenters/settings.rb
lib/voom/presenters/web_client/app.rb

The `error_logger` allows a proc to be invoked whenever a
`StandardError` is caught (for example, to log exceptions as JSON) when
the API or web client renders a Presenter.
The default `error_logger` proc mimics Sinatra's dump_errors behavior,
logging a timestamp, exception class, message, and backtrace to the rack
errors file.
Also Disable Sinatra's `dump_errors` for the web client.

Add `error_logger` setting

---

lib/voom/presenters/dsl/components/lists/line.rb
views/mdc/components/list/hidden_field.erb
views/mdc/components/list/line.erb

* Avoid mutating selectable list line checkbox names
* If a selectable list line specifies checkbox attributes or provides a checkbox component, mutate the name to append `[]` iff the provided name does not contain `[`.
* This ensures names like `hash[key]` are not mutated to `hash[key][]` and preserves existing behavior for names comprised of only word characters.
* Allow `hidden_field` within a list line
* Include `value` and `off_value` in allowed list line checkbox attributes

Selectable list line ergonomics

---

public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/base-toggle.js
views/mdc/assets/js/components/checkboxes.js
views/mdc/assets/js/components/datetime.js
views/mdc/assets/js/components/file-inputs.js
views/mdc/assets/js/components/hidden-fields.js
views/mdc/assets/js/components/mixins/dirtyable.js
views/mdc/assets/js/components/radios.js
views/mdc/assets/js/components/rich-text-area.js
views/mdc/assets/js/components/selects.js
views/mdc/assets/js/components/sliders.js
views/mdc/assets/js/components/switches.js
views/mdc/assets/js/components/text-fields.js
views/mdc/components/checkbox.erb
views/mdc/components/datetime.erb
views/mdc/components/file_input.erb
views/mdc/components/hidden_field.erb
views/mdc/components/radio_button.erb
views/mdc/components/rich_text_area.erb
views/mdc/components/select.erb
views/mdc/components/slider.erb
views/mdc/components/switch.erb
views/mdc/components/text_area.erb
views/mdc/components/text_field.erb

Previously, the values for the `data-original-value` attributes of
dirtyable elements was a plain string. This caused issues if the value
contained quotes, and was especially noticeable for text areas and rich
text areas.
With this change, the original values for dirtyable elements are stored
as a property of the component instance instead of as an attribute of
the component's DOM element with a DOMString-serialized value. This
removes the need to serialize the values at all, resolving the above
issue.
Additionally, dirtyable elements now implement the `dirtyableMixin`,
compartmentalizing much of the nonspecific original value and dirtyable
logic.
The dirtyable check implemented in 5b6828f was only affecting
checkboxes. This check has been extended to include all dirtyable
elements. …

Fix `data-original-value` values for text areas

---

public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/rich-text-area.js
views/mdc/components/rich_text_area.erb

* Register custom Blots and change Attributors per-instance instead of
once per page load
* Implement workaround for lack of support for nested list item (see
quilljs/quill#979 for context)
* Use `Editor.isBlank()` instead of checking for the presence of a
semi-empty `<p>` tag when determining whether a rich text area is
empty

Fix up various rich text editor and Quill issues

---

lib/voom/presenters/dsl/components/menu.rb
lib/voom/presenters/web_client/app.rb
public/bundle.css
views/mdc/assets/scss/components/drawer.scss
views/mdc/assets/scss/components/list.scss
views/mdc/body/dismissable-drawer.erb
views/mdc/body/drawer/item.erb
views/mdc/body/modal-drawer.erb

* `position`: `:top` (default) or `:bottom`
* bottom-positioned menu items are visually grouped and placed at the
bottom of menus, separate from other menu items
* `size`: `:normal` (default) or `:small`
* small menu items have a smaller font size
* `color`: `:primary` (default), `:secondary`, or a user-specified value

Add attributes to menu items

---

public/bundle.css
views/mdc/assets/scss/components/button.scss
views/mdc/components/buttons/button.erb

This affects only explicitly left-aligned flat button buttons (i.e., not FABs or other special button types)

Remove button padding override

---

lib/voom/presenters/dsl/components/mixins/append.rb
lib/voom/presenters/dsl/components/mixins/yield_to.rb

This allows for:
```ruby
def helper(&block)
some_collection.each do |item|
yield_to(item, &block)
end
end
helper do |item|
end
```

Let yield_to accept arguments

---

lib/voom/presenters/dsl/components/button.rb
lib/voom/presenters/dsl/components/table.rb
public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/dialogs.js
views/mdc/assets/scss/styles.scss
views/mdc/components/buttons/button.erb
views/mdc/components/dialog.erb
views/mdc/components/table.erb

Added logic to the `actionsSucceeded` handler to auto close the dialog only if the element is marked as with data-mdc-dialog-action. Per the MDC spec buttons marked in this manner are to close the dialog. This allows for the use of other buttons within the form that will not auto close the dialog.

Non action dialog buttons

---

app/demo/patterns/drag_drop.pom
lib/voom/presenters/dsl/components/chipset.rb
public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/base-component.js
views/mdc/assets/js/components/chips.js
views/mdc/assets/js/components/drag_n_drop.js
views/mdc/assets/js/components/events.js
views/mdc/assets/scss/components/drag_n_drop.scss
views/mdc/components/chip.erb
views/mdc/components/chipset.erb
views/mdc/package-lock.json

Implement `dropped` event for drag-n-drop.
The `dropped` event is fired for draggable elements when they've been dropped on a valid drop target, and is dispatched _after_ the drop target's element has dispatched its drop event.
A merge of the element-being-dragged's parameters and the drop target's parameters is used as the `dropped` event's data as follows:
* Element being dragged: `drag_params`
* Drop target element: `drop_params`
```javascript
dropped_event_data = Object.assign({}, drag_params, drop_params)
```
Any keys present on the latter override keys from the former.

Drag-n-drop `dropped` event

---

Gemfile.lock
app/demo/components/dialogs.pom
app/demo/components/menus.pom
app/demo/components/progress.pom
app/demo/events/actions/dialogs/discard.pom
app/demo/events/actions/dialogs/show_dialog.pom
app/demo/events/content_as_form.pom
lib/voom/presenters/dsl/components/actions/close_dialog.rb
lib/voom/presenters/dsl/components/dialog.rb
lib/voom/presenters/dsl/components/event.rb
lib/voom/presenters/version.rb
public/bundle.js
public/wc.js
views/mdc/assets/js/components/dialogs.js
views/mdc/assets/js/components/events.js
views/mdc/assets/js/components/events/base.js
views/mdc/assets/js/components/events/close_dialog.js
views/mdc/components/actions/close_dialog.rb
views/mdc/components/dialog.erb
views/mdc/components/form.erb

Changed dialog DSL so that dialogs must specify dialog action buttons (buttons that auto-close the dialog) be specified within an `actions` block.
Removed no longer necessary logic related to forms on a dialog.
Removed special handling of buttons within a form component.

Dialog DSL Change

---

public/bundle.css
public/wc.js
views/mdc/assets/js/wc.js

If we use a flow-matic more than once on a page that each load the same
js the second was raising errors for classes already being defined.
Preventing that with a variable now.  This will cause issues down the
road if we load 2 different components that have different scripts

Only load scripts from a flow-matic once

---

lib/voom/presenters/dsl/components/lists/line.rb
public/bundle.css
views/mdc/components/list/line.erb

This simply allows a list line action to open a dialog. I'm not sure about this behavior. There is an [expand and collapse](https://material.io/components/lists/#types) list control spec that I think would work better. But, the MDC developers have decided [not to implement](https://github.com/material-components/material-components-web/issues/46) any expand/collapse controls in the web components. I think dialogs will do for now.

Allow the use of a dialog from a list line.

---

docs/settings.md
lib/voom/presenters/api/app.rb
lib/voom/presenters/settings.rb
lib/voom/presenters/web_client/app.rb

The `before_render` configuration setting holds an array of objects
which respond to `#call/1`. Each is lazily invoked with the current
request before a Presenter is rendered (in both the web client and the
API app).
If a `before_render` item returns a non-`nil` registered Presenter name,
the Presenter identified by the returned name will be rendered instead
of the original Presenter.
If all `before_render` items return `nil`, rendering is not intercepted,
and the original Presenter is rendered unhindered.
`before_render` items can also optionally return a context hash which
will be merged with the request's original context. The returned context
hash from `before_render` will destructively overwrite keys on the
request's original context hash.
This setting and its behaviors are …

Add before_render configuration setting

---

lib/voom/presenters/dsl/components/table.rb
views/mdc/components/table/pagination.erb

When an Icon component is rendered within a `<button>` element, the Icon
component's `<i>` element never receives events (e.g. click) as they
are handled by the parent `<button>`.

Render table pagination buttons as buttons

---

public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/events/posts.js

If an action block hides an event target element (or its parent), the
`V:postFinished` event cannot bubble up to the root, as hidden
elements are no longer connected to the DOM.
This change dispatches the lifecycle event from the root instead of the
disconnected source element.
This affected the progress bar component, which was using the
`V:postFinished` event to hide itself.

Ensure lifecycle events are always dispatched

---

views/mdc/components/icon.erb

Icons rendered within text fields must have a tabindex set in order to
respond to click events. Add the tabindex attribute back with value 0.

Fix text field icons

---

lib/voom/presenters/dsl/components/text_field.rb
views/mdc/components/text_field.erb

The behavior allows clients to determine how the text field functions. The user-provided value is passed through to the client, which may or may not implement the specified behavior.
For instance, `behavior: :password` allows the MDC web client to render a masked text field that does not reveal its contents (via the `type="password"` `<input>` attribute).
To maintain backward compatibility with existing text fields, the `password` attribute is translated to `behavior: :password`.

Introduce text_field `behavior` attribute

---

public/bundle.css
public/bundle.js
public/wc.js
views/mdc/assets/js/components/events/posts.js

The contents of a POST response returns `message`, not `messages`, which was preventing the snackbar from showing when the response contained a snackbar message.

Fix snackbar callback

---

lib/voom/presenters/dsl/components/lists/line.rb

As of Ruby 2.7.0, `nil.to_s` now returns a frozen string. Attempting to
mutate it via `#<<` now results in a frozen String error.
See https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released:
>Module#name, true.to_s, false.to_s, and nil.to_s now always return a frozen String. The returned String is always the same for a given object. [Experimental] [[Feature #16150](https://bugs.ruby-lang.org/issues/16150)]

Fix frozen string mutation issue with Ruby 2.7.0

---

lib/voom/presenters/dsl/components/table.rb

Base component is html escaping all params on initialization.
Pagination then passes all those attrs when it replaces.  We want those
attrs left alone as they aren't meant to be html
I think Ideally we shouldn't be html escaping all attributes in `Components::Base` because presenters should be agnostic of the actual UI language.  I'm not sure what that will break at this point so for now I'm just unescaping where I need it.  Might also be able to unescape in `replaces`

Unescape attrs before passing them to replaces

---

lib/voom/presenters/dsl/components/text_field.rb
views/mdc/components/text_field.erb

The existing "number" behavior/type needs some additional attributes to treat the input as a float for currency input.

Allow "currency" as a behavior in text fields 

---

lib/voom/presenters/dsl/components/text_field.rb

Having a blank behavior was leaving us with `type=value="The" portal`

Need quotes around behavior

---

lib/voom/presenters/dsl/definition.rb
lib/voom/presenters/registry.rb
lib/voom/presenters/web_client/app.rb

Add an `options` parameter to Voom::Presenters.define(). Currently only supports an option to set the X-Frame-Options header to 'ALLOWALL'

Presenter definition options

---

lib/voom.rb

Loading the file manually was avoiding zeitwerk causing it to then load
again when referenced by class, leaving 2 filewatchers running and
printing.

fix: double file edit prints caused by multiple file watchers
