lib/voom/presenters/dsl/components/content.rb, lib/voom/presenters/dsl/components/event.rb, lib/voom/presenters/dsl/components/list.rb, lib/voom/presenters/dsl/components/text_field.rb, lib/voom/presenters/helpers/date.rb, lib/voom/presenters/helpers/rails/model_table.rb, lib/voom/presenters/helpers/time.rb, public/bundle.css, public/bundle.js, views/mdc/assets/js/components/base-container.js, views/mdc/assets/js/components/content.js, views/mdc/assets/js/components/dialogs.js, views/mdc/assets/js/components/events/base.js, views/mdc/assets/js/components/events/toggle_visibility.js, views/mdc/assets/js/components/forms.js, views/mdc/assets/js/components/grid.js, views/mdc/assets/js/components/icon-toggles.js, views/mdc/assets/js/components/initialize.js, views/mdc/assets/js/components/steppers.js, views/mdc/assets/scss/app.scss, views/mdc/assets/scss/components/content.scss, views/mdc/assets/scss/components/fab.scss, views/mdc/assets/scss/components/list.scss, views/mdc/components/card.erb, views/mdc/components/checkbox.erb, views/mdc/components/content.erb, views/mdc/components/dialog.erb, views/mdc/components/grid.erb, views/mdc/components/list.erb, views/mdc/components/text_field.erb
Includes refactor to introduce container base.
=> Refactor of tags to work with components of any kind.

app/demo/events/actions/loads.pom, app/demo/events/actions/posts.pom, lib/voom/presenters/dsl/components/actions/posts.rb, lib/voom/presenters/dsl/components/actions/updates.rb, views/mdc/components/actions/clear.rb, views/mdc/components/actions/delete.rb, views/mdc/components/actions/dialog.rb, views/mdc/components/actions/loads.rb, views/mdc/components/actions/navigates.rb, views/mdc/components/actions/post.rb, views/mdc/components/actions/remove.rb, views/mdc/components/actions/replaces.rb, views/mdc/components/actions/snackbar.rb, views/mdc/components/actions/stepper.rb, views/mdc/components/actions/toggle_visibility.rb, views/mdc/components/actions/update.rb, views/mdc/components/event.erb
This adds classes for each action that defines the data to pass to its javascript class of the same name. It then handles the parameters correctly for each type.
=> Issue #36 - Double parameters + 'null's.

public/bundle.js, views/mdc/.eslintrc.yml, views/mdc/assets/js/components/datetime.js, views/mdc/assets/js/components/events/posts.js, views/mdc/assets/js/config.js, views/mdc/assets/js/utils/config.js, views/mdc/body/header.erb, views/mdc/components/typography.erb, views/mdc/layout.erb
Fixes #48:
* The datetime component's popup can now be toggled by clicking on the component's input element.
=> (#48) Change datetime component behavior to toggle on click

public/bundle.js, views/mdc/assets/js/app.js, views/mdc/package-lock.json, views/mdc/package.json
This ensures compatibility with Microsoft Edge.
=> Add babel-polyfill

app/demo/components/file_inputs.pom, app/demo/components/nav/menu.pom, lib/voom/presenters/dsl/components/file_input.rb, lib/voom/presenters/dsl/components/form.rb, lib/voom/presenters/dsl/components/grid.rb, lib/voom/presenters/dsl/components/mixins/file_inputs.rb, public/bundle.css, public/bundle.js, views/mdc/assets/js/components/file-inputs.js, views/mdc/assets/js/components/initialize.js, views/mdc/assets/scss/app.scss, views/mdc/assets/scss/components/file-input.scss, views/mdc/components/file_input.erb
This introduces a file input component; other functionality
will likely be needed, but this first take has the basics.
Things to consider will be keyboard support (possibly with an
altogether different strategy for this), hinting/errors/etc.
Drag and drop is supported within the field area. We might also
consider a different layout that presents this as a drag and
drop "zone."
It's been added to the demos as well.
=> Add file input component

lib/voom/presenters/dsl/components/table.rb, public/bundle.js, views/mdc/assets/js/components/selects.js, views/mdc/package-lock.json, views/mdc/package.json
* If a select somehow has no options it causes `prepareSubmit` to throw a fatal error
* Fix per page select and range display in table pagination
* Recreate package-lock.json - an NPM package (har-validation@5.1.2) disappeared from the internet and causes `npm install` to fail
=> Fix a few bugs

Gemfile, Gemfile.lock, app/demo/events/actions/last_response.pom, app/demo/events/nav/drawer.pom, bin/console, lib/hash/deep_transform_values.rb, lib/hash_ext/traverse.rb, lib/voom/presenters/dsl/components/actions/base.rb, lib/voom/presenters/dsl/components/mixins/last_response.rb, views/mdc/components/actions/mixins/expand_hash.rb, views/mdc/components/actions/post.rb, views/mdc/components/actions/snackbar.rb
The url is still getting built with the expanded parameter info.
Seperating that from standard parameters is a second pass/refactor.
=> First pass at expanding dynamic action values in the components.

app/demo/components/toggles.pom, lib/voom/presenters/dsl/components/switch.rb, public/bundle.js, views/mdc/assets/js/components/switches.js, views/mdc/components/switch.erb
=> Add ability to set an on and off value for a switch.

Gemfile.lock, app/demo/events/actions/last_response.pom, lib/voom/presenters/dsl/components/card.rb, lib/voom/presenters/pluggable.rb, lib/voom/railtie.rb, public/bundle.css, public/bundle.js, views/mdc/assets/js/components/events/base.js, views/mdc/assets/js/components/events/loads.js, views/mdc/assets/js/components/events/posts.js, views/mdc/assets/js/components/events/replaces.js, views/mdc/assets/js/components/file-inputs.js, views/mdc/assets/scss/components/card.scss, views/mdc/assets/scss/components/file-input.scss, views/mdc/components/actions/loads.rb, views/mdc/components/actions/replaces.rb, views/mdc/components/card.erb
* Fixed some of the styling for file-input component
* Added support for last response to replaces and loads actions
* Modified pluggable to load rather than require plugins. Fixes issue with plugins getting unloaded after pom changes during development.
=> 1) Last Response added to replaces and submits actions. 2) Added id and hidden to card media section

app/demo/components/toggles.pom, lib/voom/presenters/dsl/components/switch.rb, lib/voom/presenters/dsl/components/toggle_base.rb, public/bundle.css, public/bundle.js, views/mdc/assets/js/components/base-toggle.js, views/mdc/assets/js/components/checkboxes.js, views/mdc/assets/js/components/icon-toggles.js, views/mdc/assets/js/components/radios.js, views/mdc/assets/js/components/switches.js, views/mdc/components/checkbox.erb, views/mdc/components/icon_toggle.erb, views/mdc/components/radio_button.erb, views/mdc/components/switch.erb
Ensure all toggle components (checkboxes, icon toggles, radio buttons, and switches) support the `value` and `off_value` attributes.
=> Base toggle

views/mdc/components/text_field.erb
See https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7
=> Disable autocomplete for Chromium-based browsers

public/bundle.css, views/mdc/assets/scss/components/fab.scss
This remedies FABs changing position relative to their container's size.
=> Fix FAB positioning

public/bundle.js, public/wc.js, views/mdc/assets/js/wc.js, views/mdc/package-lock.json
This allows the admin to listen for the event and cleanly deal from
there
=> All credit to Nick for sending an event when a flow-matic comp is loaded

lib/voom/presenters/dsl/components/image.rb, public/bundle.css, views/mdc/assets/scss/components/image.scss, views/mdc/components/button.erb, views/mdc/components/image.erb
Expand Image component's attributes
* Add min and max width and height
* Add fit for controlling aspect ratio (default: contain)
* Add description for accessibility
* Set a default position: center
* Ensure unit-less size values are treated as pixel values
=> Image attributes

public/bundle.css, views/mdc/assets/scss/styles.scss
See: https://github.com/material-components/material-components-web/issues/4629
=> Add temporary workaround for Chromium list hover state opacity issue

lib/voom/presenters/dsl/components/header.rb, views/mdc/body/header.erb
Valid placements include `static` (the default) and `fixed`.
=> Allow for specification of header placement

public/bundle.js, public/wc.js, views/mdc/assets/js/components/lists.js, views/mdc/components/list/header.erb
- Apply styles on "select all results" control so it gets picked up on POSTs
- Update list initialization so elements added when "load more" is used are included.
=> Fix select all controls on selectable list.

public/bundle.js, public/wc.js, views/mdc/assets/js/components/events/replaces.js
=> Fix InputEvent

public/bundle.js, public/wc.js, views/mdc/assets/js/components/datetime.js
Compare dates in the same format when checking if a datetime field isDirty.
=> Fix bug in datetime component

public/bundle.js, public/wc.js, views/mdc/assets/js/components/base-component.js, views/mdc/assets/js/components/events.js, views/mdc/assets/js/components/events/replaces.js, views/mdc/assets/js/components/menus.js, views/mdc/assets/js/components/uninitialize.js, views/mdc/components/menu.erb
Refactored menu component to handle addition/removal of its events independently from the global eventInit code.
Added beginning stages of managing component cleanup via destroy method. Only being used by menu component pending a larger rework of the component lifecycle.
=> Menu positioning

app/demo/components/sliders.pom, lib/voom/presenters/dsl/components/input.rb, lib/voom/presenters/dsl/components/text_field.rb, lib/voom/presenters/dsl/components/toggle_base.rb, public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/js/components/rich-text-area.js, views/mdc/assets/scss/components/menu.scss, views/mdc/assets/scss/components/rich-text-area.scss, views/mdc/components/file_input.erb, views/mdc/components/menu.erb, views/mdc/components/rich_text_area.erb, views/mdc/components/select.erb, views/mdc/components/slider.erb, views/mdc/components/text_area.erb, views/mdc/components/text_field.erb
Some Input components were not capable of being disabled or had partial
implementations.
=> Implement disabled attribute for Input components

public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/scss/styles.scss, views/mdc/package-lock.json
Button components with `hidden: true` were still visible. The `display: inline-flex` style in .mdc-button was overriding the `display: none` in .v-hidden
=> Fix hidden option in button components

app/demo/components/text_fields.pom, lib/voom/presenters/dsl/components/text_field.rb, public/bundle.js, public/wc.js, views/mdc/assets/js/components/text-fields.js, views/mdc/components/text_field.erb
Defaults to `mixed` but can be set to `upper` or `lower` to force all input to be automatically converted to upper or lower case on input.
=> Added `case_type` attribute to text_field component. 

lib/voom/presenters/dsl/protect_from_forgery.rb, lib/voom/presenters/dsl/user_interface.rb, lib/voom/presenters/settings.rb, public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/js/components/events/posts.js, views/mdc/layout.erb
...events. The token is compatible with Rails' built-in CSRF protection.
=> Provide CSRF authenticity token meta tags and pass through on POST

public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/js/components/events/posts.js, views/mdc/assets/js/components/rich-text-area.js
Put a flag in the header to signal to the WAF that the request contains HTML/Rich Text or anything that requires special treatment by the XSS checks.
=> Flag HTML in POSTs

lib/voom/presenters/dsl/components/card.rb, public/bundle.css, views/mdc/assets/scss/styles.scss, views/mdc/components/card.erb
Ran into issues with hiding button elements within a dialog. Added some additional attributes to the v-hidden class to make an element appear/act hidden.
Unrelated but I also added the ability to mark a `Card` component as `hidden`. This eliminates the need to wrap a `card` in a `content` block and mark it as hidden.
=> Alternate css hide strategy

app/demo/components/selects.pom, lib/voom/presenters/dsl/components/select.rb, views/mdc/components/icon.erb, views/mdc/components/select.erb
Small change to support leading icons in select components.
=> Added icons to the select component

public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/js/components/datetime.js
I needed an event after the user had selected both sides for a date
range.  Change fires after the first one, when the calendar is still
open
=> Dispatch an event when the calendar picker is closed

app/demo/plugins/index.pom, bin/presenters, lib/voom/presenters/cli.rb, lib/voom/presenters/generators/inflectors.rb, lib/voom/presenters/generators/plugin.rb, lib/voom/presenters/generators/templates/plugin/.gitignore, lib/voom/presenters/generators/templates/plugin/Gemfile, lib/voom/presenters/generators/templates/plugin/LICENSE.txt.tt, lib/voom/presenters/generators/templates/plugin/README.md, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/components/actions/action.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/components/actions/dsl.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/components/component.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/components/dsl.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/helpers/helper.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/plugin.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/web_client/components/actions/data.rb.tt, lib/voom/presenters/generators/templates/plugin/lib/voom/presenters/plugins/web_client/components/render.rb.tt, lib/voom/presenters/generators/templates/plugin/presenter_plugin.gemspec.tt, lib/voom/presenters/generators/templates/plugin/views/assets/css/components/component.css.tt, lib/voom/presenters/generators/templates/plugin/views/assets/js/components/actions/action.js.tt, lib/voom/presenters/generators/templates/plugin/views/assets/js/components/component.js.tt, lib/voom/presenters/generators/templates/plugin/views/components/component.erb.tt, lib/voom/presenters/generators/templates/plugin/views/components/component_header.erb.tt, presenters.gemspec
Added a cli `presenters` that can generate a plugin.
Usage:
>presenters generate plugin <your plugin name>
The generator generates a plugin with all features available. The layout is the same as the presenters source itself, making it easier to map between the two. (Hopefully)
=> Plugin Generator

public/bundle.css, public/bundle.js, public/wc.js, views/mdc/assets/js/components/events/posts.js, views/mdc/assets/js/utils/form-data.js, views/mdc/package-lock.json
Previously, passing an object as a parameter through an event dispatch would results in `key: object Object`. This utility function will transform objects into nested hashes.
=> fix: Handle nested objects in event parameters from past action.
